name: "Lint documentation"

on:
  push:
  pull_request:
    branches: [main]
  workflow_call:

env:
  UV_LOCKED: true

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vale-cli/vale-action@v2.1.1
        with:
          files: "docs/,lso/"
          separator: ","
          fail_on_error: true
          vale_flags: "--glob=*.{md,py}"
